"""empty message

Revision ID: ba8a67a29631
Revises: f8f6e5b4e646
Create Date: 2018-11-03 12:32:44.528483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8a67a29631'
down_revision = 'f8f6e5b4e646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('test', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
